# Generated by Django 5.2.6 on 2025-09-21 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_value",
                    models.IntegerField(
                        choices=[
                            (1, "Very Unpleasant"),
                            (2, "Unpleasant"),
                            (3, "Slightly Unpleasant"),
                            (4, "Neutral"),
                            (5, "Slightly Pleasant"),
                            (6, "Pleasant"),
                            (7, "Very Pleasant"),
                        ]
                    ),
                ),
                ("mood_label", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood Entry",
                "verbose_name_plural": "Mood Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
